# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.4.0"

# Ruby 3.4+ ships these as bundled gems; Jekyll and dependencies need them.
gem "base64"
gem "bigdecimal"
gem "csv"

gem "jekyll", "~> 4.0.0"
gem "webrick", "~> 1.8"
gem "minima", "~> 2.5.1"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?
