name: Website Builder

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency: website-build

# Run this workflow every time a new commit pushed to your repository,
# and periodically, to pick up any other updates that may have occurred - 
# e.g. in the data repository.
# Bear in mind that if there are no pushes to this repository in 3 months, then this action gets disabled,
# and that stops the scheduled runs, but also the ones triggered by pushes, so it might not be ideal to 
# have these both in the same action, if that's an option
on: 
  push:
    branches:
      - master
  workflow_dispatch:
    # Allow it to be run manually - useful for testing?

jobs:
  website-builder:
    name: Build the website from this repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Ruby with mise
        uses: jdx/mise-action@v3
        with:
          install: true

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy dependencies to Website directory
        run: bash ./build/website/copy-assets.sh
        shell: bash

      - name: Install Ruby build dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y --no-install-recommends libffi-dev
        shell: bash

      - name: Build the Jekyll site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          jekyll_src: website
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        if: github.repository == 'fraz3alpha/running-challenges' && github.actor != 'dependabot[bot]'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/_site
          force_orphan: true
